function P = params_pack(p)
P = [p.L; p.bodyLen; p.bodyWid; p.bodyCtrOff; p.coneR; ...
     p.dMax; p.dRateMax; p.tauSteer; ...
     p.aLatMax; p.aAccMax; p.aBrkMax; p.vMax; ...
     p.kpV; p.kiV; ...
     p.Ld0; p.kv; p.ke; p.kSoft; p.searchWin];
end
